### ISSUE TITLE
Automate Subsystem setup in makefile

### ISSUE THREAD

**Issue by amagid** [eradani-inc/eradani-connect-template#6]
CRTUSRPRF USRPRF(ECNCT) INLPGM(QSYS/QCMD) TEXT('Eradani Connect user profile') JOBD(QGPL/QDFTJOBD) MSGQ(QUSRSYS/ECNCTOUT) PWDEXPITV(*NOMAX)

CHGOBJOWN OBJ(ECNCT) OBJTYPE(*LIB) NEWOWN(ECNCT)

CRTLIB LIB(ECNCTSBS) TEXT('Eradani Connect Subsystem data')

CHGOBJOWN OBJ(ECNCTSBS) OBJTYPE(*LIB) NEWOWN(ECNCT)

CRTCLS CLS(ECNCTSBS/ECNCTOUT) TEXT('Class for Eradani Connect subsystem')

CRTJOBQ JOBQ(ECNCTSBS/ECNCTOUT) TEXT('Job queue for Eradani Connect jobs')

CRTJOBD JOBD(ECNCTSBS/ECNCTOUT) JOBQ(ECNCTSBS/ECNCTOUT) TEXT('Eradani Connect job description') USER(ECNCT) PRTTXT('Eradani Connect jobs') RQSDTA('call PGM(QP2SHELL) PARM(''/QOpenSys/opt/eradani/ecc-template/start.sh'')')

CRTSBSD SBSD(ECNCTSBS/ECNCTOUT) POOLS((1 *BASE)) MAXJOBS(30) TEXT('Eradani Connect subsystem description')

ADDJOBQE SBSD(ECNCTSBS/ECNCTOUT) JOBQ(ECNCTSBS/ECNCTOUT) MAXACT(15)

ADDRTGE SBSD(ECNCTSBS/ECNCTOUT) SEQNBR(9999) CMPVAL(*ANY) PGM(QSYS/QCMD) CLS(ECNCTSBS/ECNCTOUT)

ADDAJE SBSD(ECNCTSBS/ECNCTOUT) JOB(ECNCTOUT) JOBD(ECNCTSBS/ECNCTOUT)

CHGOWN OBJ('/QOpenSys/opt/eradani/') NEWOWN(ECNCT) SUBTREE(*ALL)

**Comment by dromonaco** [comment]
Also strip CR's from the script that starts the node server and chmod permissions

**Comment by amagid** [comment]
Obsoleted by installer script.
